version: '3.9'
services:
  ui:
    build: pmdash_ui/
    container_name: pmdash-ui
    ports: 
      - "${UI_HOST_EXPOSED}:${UI_PORT_EXPOSED}"
    expose:
      - ${UI_PORT_EXPOSED}
    environment:
      - API_URL=${API_URL}
    mem_limit: ${UI_MEM_LIMIT}
    networks:
      - pmdash
  
  api:
    build: pmdash_api/
    container_name: pmdash-api
    ports: 
      - "${API_HOST_EXPOSED}:${API_PORT_EXPOSED}"
    expose:
      - ${API_PORT_EXPOSED}
    environment:
      - MONGO_URL=${MONGO_URL}
      - MONGO_PORT=${MONGO_PORT_EXPOSED}
      - MONGO_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_CLUSTER_NAME=${MONGO_CLUSTER_NAME}
    mem_limit: ${API_MEM_LIMIT}
    networks:
      - pmdash
  
  mongodb:
    image: mongo:latest
    container_name: pmdash-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - ${MONGO_HOST_EXPOSED}:${MONGO_PORT_EXPOSED}
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - pmdash

volumes:
  mongodb_data_container:

networks:
  pmdash:
    name: pmdash 